### ISSUE TITLE
Fix syntax error at `login.js`

### ISSUE THREAD

**Issue by nooreldeensalah** [ElGarash/meetings#24]
https://github.com/ElGarash/meetings/blob/a22b76592da909429abbc5baecaefcaea4cdbcec/src/login.js#L7

This function has an empty body.

Properly close the body to look like this.
![image](https://user-images.githubusercontent.com/61914159/128639573-bb76d7c6-dc76-49b9-928e-d4c5de877a80.png)

**Comment by ahmed-abdulhuy** [comment]
I had fixed it
