### ISSUE TITLE
Use TitleCase naming convention at `meeting labels` input field.

### ISSUE THREAD

**Issue by nooreldeensalah** [ElGarash/meetings#27]
![image](https://user-images.githubusercontent.com/61914159/128639878-4795ee45-9f2d-4e94-888d-6bf78806225f.png)

**Comment by ahmed-abdulhuy** [comment]
I think I use title case.
can you give an example?

**Comment by nooreldeensalah** [comment]
Title case is a naming convention.
`meeting labels` in title case would look like this
![image](https://user-images.githubusercontent.com/61914159/128727978-9f2e1790-e7b1-44a1-92b8-18b83533e17b.png)

**Comment by ahmed-abdulhuy** [comment]
OK, I thought you talk about the labels placeholder.
