### ISSUE TITLE
Pick a better expressive name for the `CLOSE MEETING` button.

### ISSUE THREAD

**Issue by nooreldeensalah** [ElGarash/meetings#28]
The name `CLOSE MEETING` might be deceptive, because it doesn't actually end a meeting, what it does is that it returns to the active meetings and creating rooms page.

**Comment by ahmed-abdulhuy** [comment]
Is "Leave room" better ?

**Comment by nooreldeensalah** [comment]
Yes, it's more accurate.

**Comment by ahmed-abdulhuy** [comment]
OK
